### ISSUE TITLE
Plugin does not compile due to offine mode

### ISSUE THREAD

**Issue by derliebemarcus** [simonnagl/netdata-java-orchestrator#61]
Hi there,

in line 225 of netdata-java-orchestrator-installer.sh, Maven is configured to run in offline mode. As a result, the dependencies cannot be resolved properly and the installation fails. Removing the -o switch solves the problem.

Cheers,
marcus

**Comment by simonnagl** [comment]
Thank you very much for the bug report, Marcus. The flag was committed by accident. I will fix this soon. Sorry for this bug and trouble.

**Comment by simonnagl** [comment]
I just pushed the changes. If you have any further problems or anything to mention or to suggest please open a new issue.
