### ISSUE TITLE
How to get alarms

### ISSUE THREAD

**Issue by venkatanikil** [simonnagl/netdata-java-orchestrator#65]
Hi,
I am using Netdata 1.17.0 and Java Version 1.8 
and i installed this "netdata-java-orchestrator" using the script  "netdata-java-orchestrator-installer.sh" as mentioned in "README.md" and everything is successfully executed and i got "JMX-CHARTS" in the Netdata but i didn't the "Alarms". If there is any procedure to configure Alarms please help me out 
 
@simonnagl

**Comment by simonnagl** [comment]
Hi @venkatanikil,
I am happy to hear you could install the orchestrator successfully. The orchestrator does not contain any health configuration files at the moment. This is the reason you are not getting any "alarms".
I am aware that this is needed. Check https://github.com/simonnagl/netdata-java-orchestrator/issues/19!
Writing health configuration for netdata is "just" writing a special config file. If you invest your time and write some general health alarms, it would be nice if you share them.

You can either create a pull request or just comment the code into #19. 

I will close this issue as answered and duplicate to #19. If you have any further questions or anything else feel free to comment again!
